### PR TITLE
Remove sample rate parameter usage

### PR DESCRIPTION
**Pull request by reuben**
See mozilla/DeepSpeech#2420

### CODE REVIEW

**Comment by est31** [comment]
Build is failing. I think the submodule needs to be updated.

**Comment by reuben** [comment]
I have no idea how to do that 😬

**Comment by reuben** [comment]
Ah, nevermind, I was messing up the `git submodule` params.

**Comment by reuben** [comment]
Green!

**Review by est31 — APPROVED** [review]
Thanks!

**Pull request merged**
