### PR TITLE
update dependencies so it builds

### PR DESCRIPTION
**Pull request by russelltg**
It didn't build because the sample dependency for audrey didn't build for some reason--I just updated audrey to the latest version which removes the sample crate entirely for the newer dasp_* crates.

### CODE REVIEW

**Review by est31 — APPROVED** [review]
Thanks!

**Review by est31 — CHANGES_REQUESTED** [review]
Wait a minute. CI is failing. The examples seem to need updating.

**Comment by russelltg** [comment]
I'll fix em up

**Comment by russelltg** [comment]
I can re-run the bg command--the bindgen tests still pass so it should be good to go.

**Comment by est31** [comment]
Can you remove the bg changes? I'd like it done in a separate PR. Also it'd be great if you also ran the tool to update the bindings.

**Review by est31 — APPROVED** [review]
Whatever, I'll just merge this. Thanks again!

**Pull request merged**
